<a href="https://colab.research.google.com/github/varun0852/for-study/blob/master/NLP_Theory_Coding_Chapter_18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk

nltk.download("stopwords")
nltk.download("wordnet")

from nltk.corpus import stopwords
from nltk.stem import LancasterStemmer , WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix , classification_report
from sklearn.ensemble import RandomForestClassifier

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
# from google.colab import files
# uploaded = files.upload()

Saving spam.csv to spam.csv

In [ ]:
df = pd.read_csv("spam.csv" , encoding="cp1252")
df

        v1  ... Unnamed: 4
0      ham  ...        NaN
1      ham  ...        NaN
2     spam  ...        NaN
3      ham  ...        NaN
4      ham  ...        NaN
...    ...  ...        ...
5567  spam  ...        NaN
5568   ham  ...        NaN
5569   ham  ...        NaN
5570   ham  ...        NaN
5571   ham  ...        NaN

[5572 rows x 5 columns]

# CLEANING

In [ ]:
df1 = df[["v2" , "v1"]]
df1

                                                     v2    v1
0     Go until jurong point, crazy.. Available only ...   ham
1                         Ok lar... Joking wif u oni...   ham
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam
3     U dun say so early hor... U c already then say...   ham
4     Nah I don't think he goes to usf, he lives aro...   ham
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...  spam
5568              Will Ì_ b going to esplanade fr home?   ham
5569  Pity, * was in mood for that. So...any other s...   ham
5570  The guy did some bitching but I acted like i'd...   ham
5571                         Rofl. Its true to its name   ham

[5572 rows x 2 columns]

In [ ]:
df1.isna().sum()

v2    0
v1    0
dtype: int64

In [ ]:
df1[df1.duplicated()]

                                                     v2    v1
102   As per your request 'Melle Melle (Oru Minnamin...   ham
153   As per your request 'Melle Melle (Oru Minnamin...   ham
206   As I entered my cabin my PA said, '' Happy B'd...   ham
222                              Sorry, I'll call later   ham
325                    No calls..messages..missed calls   ham
...                                                 ...   ...
5524  You are awarded a SiPix Digital Camera! call 0...  spam
5535  I know you are thinkin malaria. But relax, chi...   ham
5539                         Just sleeping..and surfing   ham
5553                        Hahaha..use your brain dear   ham
5558                             Sorry, I'll call later   ham

[403 rows x 2 columns]

In [ ]:
df2 = df1.drop_duplicates(keep="first")
df2

                                                     v2    v1
0     Go until jurong point, crazy.. Available only ...   ham
1                         Ok lar... Joking wif u oni...   ham
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam
3     U dun say so early hor... U c already then say...   ham
4     Nah I don't think he goes to usf, he lives aro...   ham
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...  spam
5568              Will Ì_ b going to esplanade fr home?   ham
5569  Pity, * was in mood for that. So...any other s...   ham
5570  The guy did some bitching but I acted like i'd...   ham
5571                         Rofl. Its true to its name   ham

[5169 rows x 2 columns]

In [ ]:
df2["v2"].isna().sum()

np.int64(0)

In [ ]:
# Converting into lower case
lower_case = []
for text in df2["v2"]:
  lower_case.append(text.lower())

In [ ]:
# Removing Punctuations
punctuation_no_removed = []
for text in lower_case:
  punctuation_no_removed.append(re.sub('[^a-zA-Z]' , ' ' , text))

In [ ]:
# Tokenizeding
tokenized = []
for text in punctuation_no_removed:
  tokenized.append(text.split())

In [ ]:
# Removing stopwords
parent_lst = []
for token_list in tokenized:
  stop_word_removed = []
  for word in token_list:
    if word not in stopwords.words("english"):
      stop_word_removed.append(word)
  parent_lst.append(stop_word_removed)

In [ ]:
lancaster = LancasterStemmer()

In [ ]:
lancaster_stemmed = []
for stop_word_removed in parent_lst:
  stemmed_token_lst = []
  for token in stop_word_removed:
    stemmed_token = lancaster.stem(token)
    stemmed_token_lst.append(stemmed_token)
  lancaster_stemmed.append(stemmed_token_lst)

In [ ]:
lemmatizer = WordNetLemmatizer()

In [ ]:
wordnet_lemmatized = []
for stop_word_removed in parent_lst:
    lemmatized_token_lst = []
    for token in stop_word_removed:
        lemmatized_token = lemmatizer.lemmatize(token)
        lemmatized_token_lst.append(lemmatized_token)
    wordnet_lemmatized.append(lemmatized_token_lst)

In [ ]:
lancaster_stemmed_text = []
for stemmed_token_lst in lancaster_stemmed:
  text = ' '.join(stemmed_token_lst)
  lancaster_stemmed_text.append(text)

In [ ]:
wordnet_lemmatized_text = []
for lemmatized_token_lst in wordnet_lemmatized:
  text = ' '.join(lemmatized_token_lst)
  wordnet_lemmatized_text.append(text)

In [ ]:
df2["lancaster_stemmed_text"] = lancaster_stemmed_text
df2["wordnet_lemmatized_text"] = wordnet_lemmatized_text

/tmp/ipython-input-2889360920.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["lancaster_stemmed_text"] = lancaster_stemmed_text
/tmp/ipython-input-2889360920.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["wordnet_lemmatized_text"] = wordnet_lemmatized_text

In [ ]:
df2

                                                     v2  ...                            wordnet_lemmatized_text
0     Go until jurong point, crazy.. Available only ...  ...  go jurong point crazy available bugis n great ...
1                         Ok lar... Joking wif u oni...  ...                            ok lar joking wif u oni
2     Free entry in 2 a wkly comp to win FA Cup fina...  ...  free entry wkly comp win fa cup final tkts st ...
3     U dun say so early hor... U c already then say...  ...                u dun say early hor u c already say
4     Nah I don't think he goes to usf, he lives aro...  ...                nah think go usf life around though
...                                                 ...  ...                                                ...
5567  This is the 2nd time we have tried 2 contact u...  ...  nd time tried contact u u pound prize claim ea...
5568              Will Ì_ b going to esplanade fr home?  ...                          b going esplanade fr home
5569  Pity, * was in mood for that. So...any other s...  ...                               pity mood suggestion
5570  The guy did some bitching but I acted like i'd...  ...  guy bitching acted like interested buying some...
5571                         Rofl. Its true to its name  ...                                     rofl true name

[5169 rows x 4 columns]

In [ ]:
df2.isna().sum()

v2                         0
v1                         0
lancaster_stemmed_text     0
wordnet_lemmatized_text    0
dtype: int64

In [ ]:
def generate_ngrams(doc , n=2):
  tokens = doc.split()
  return [' '.join(tokens[i:i+n]) for i in range(len(tokens)-n+1)]

for i, doc in enumerate(df2["wordnet_lemmatized_text"]):
  bigrams = generate_ngrams(doc , n=2)
  print(f"Document {i+1} 2-grams (sequential): {bigrams}")

Document 1 2-grams (sequential): ['go jurong', 'jurong point', 'point crazy', 'crazy available', 'available bugis', 'bugis n', 'n great', 'great world', 'world la', 'la e', 'e buffet', 'buffet cine', 'cine got', 'got amore', 'amore wat']
Document 2 2-grams (sequential): ['ok lar', 'lar joking', 'joking wif', 'wif u', 'u oni']
Document 3 2-grams (sequential): ['free entry', 'entry wkly', 'wkly comp', 'comp win', 'win fa', 'fa cup', 'cup final', 'final tkts', 'tkts st', 'st may', 'may text', 'text fa', 'fa receive', 'receive entry', 'entry question', 'question std', 'std txt', 'txt rate', 'rate c', 'c apply']
Document 4 2-grams (sequential): ['u dun', 'dun say', 'say early', 'early hor', 'hor u', 'u c', 'c already', 'already say']
Document 5 2-grams (sequential): ['nah think', 'think go', 'go usf', 'usf life', 'life around', 'around though']
Document 6 2-grams (sequential): ['freemsg hey', 'hey darling', 'darling week', 'week word', 'word back', 'back like', 'like fun', 'fun still', 'still tb', 'tb ok', 'ok xxx', 'xxx std', 'std chgs', 'chgs send', 'send rcv']
Document 7 2-grams (sequential): ['even brother', 'brother like', 'like speak', 'speak treat', 'treat like', 'like aid', 'aid patent']
Document 8 2-grams (sequential): ['per request', 'request melle', 'melle melle', 'melle oru', 'oru minnaminunginte', 'minnaminunginte nurungu', 'nurungu vettam', 'vettam set', 'set callertune', 'callertune caller', 'caller press', 'press copy', 'copy friend', 'friend callertune']
Document 9 2-grams (sequential): ['winner valued', 'valued network', 'network customer', 'customer selected', 'selected receivea', 'receivea prize', 'prize reward', 'reward claim', 'claim call', 'call claim', 'claim code', 'code kl', 'kl valid', 'valid hour']
Document 10 2-grams (sequential): ['mobile month', 'month u', 'u r', 'r entitled', 'entitled update', 'update latest', 'latest colour', 'colour mobile', 'mobile camera', 'camera free', 'free call', 'call mobile', 'mobile update', 'update co', 'co free']
Document 11 2-grams (sequential): ['gonna home', 'home soon', 'soon want', 'want talk', 'talk stuff', 'stuff anymore', 'anymore tonight', 'tonight k', 'k cried', 'cried enough', 'enough today']
Document 12 2-grams (sequential): ['six chance', 'chance win', 'win cash', 'cash pound', 'pound txt', 'txt csh', 'csh send', 'send cost', 'cost p', 'p day', 'day day', 'day tsandcs', 'tsandcs apply', 'apply reply', 'reply hl', 'hl info']
Document 13 2-grams (sequential): ['urgent week', 'week free', 'free membership', 'membership prize', 'prize jackpot', 'jackpot txt', 'txt word', 'word claim', 'claim c', 'c www', 'www dbuk', 'dbuk net', 'net lccltd', 'lccltd pobox', 'pobox ldnw', 'ldnw rw']
Document 14 2-grams (sequential): ['searching right', 'right word', 'word thank', 'thank breather', 'breather promise', 'promise wont', 'wont take', 'take help', 'help granted', 'granted fulfil', 'fulfil promise', 'promise wonderful', 'wonderful blessing', 'blessing time']
Document 15 2-grams (sequential): ['date sunday']
Document 16 2-grams (sequential): ['xxxmobilemovieclub use', 'use credit', 'credit click', 'click wap', 'wap link', 'link next', 'next txt', 'txt message', 'message click', 'click http', 'http wap', 'wap xxxmobilemovieclub', 'xxxmobilemovieclub com', 'com n', 'n qjkgighjjgcbl']
Document 17 2-grams (sequential): ['oh k', 'k watching']
Document 18 2-grams (sequential): ['eh u', 'u remember', 'remember spell', 'spell name', 'name yes', 'yes v', 'v naughty', 'naughty make', 'make v', 'v wet']
Document 19 2-grams (sequential): ['fine way', 'way u', 'u feel', 'feel way', 'way gota', 'gota b']
Document 20 2-grams (sequential): ['england v', 'v macedonia', 'macedonia dont', 'dont miss', 'miss goal', 'goal team', 'team news', 'news txt', 'txt ur', 'ur national', 'national team', 'team eg', 'eg england', 'england try', 'try wale', 'wale scotland', 'scotland txt', 'txt poboxox', 'poboxox w', 'w wq']
Document 21 2-grams (sequential): ['seriously spell', 'spell name']
Document 22 2-grams (sequential): ['going try', 'try month', 'month ha', 'ha ha', 'ha joking']
Document 23 2-grams (sequential): ['pay first', 'first lar', 'lar da', 'da stock', 'stock comin']
Document 24 2-grams (sequential): ['aft finish', 'finish lunch', 'lunch go', 'go str', 'str lor', 'lor ard', 'ard smth', 'smth lor', 'lor u', 'u finish', 'finish ur', 'ur lunch', 'lunch already']
Document 25 2-grams (sequential): ['ffffffffff alright', 'alright way', 'way meet', 'meet sooner']
Document 26 2-grams (sequential): ['forced eat', 'eat slice', 'slice really', 'really hungry', 'hungry tho', 'tho suck', 'suck mark', 'mark getting', 'getting worried', 'worried know', 'know sick', 'sick turn', 'turn pizza', 'pizza lol']
Document 27 2-grams (sequential): ['lol always', 'always convincing']
Document 28 2-grams (sequential): ['catch bus', 'bus frying', 'frying egg', 'egg make', 'make tea', 'tea eating', 'eating mom', 'mom left', 'left dinner', 'dinner feel', 'feel love']
Document 29 2-grams (sequential): ['back amp', 'amp packing', 'packing car', 'car let', 'let know', 'know room']
Document 30 2-grams (sequential): ['ahhh work', 'work vaguely', 'vaguely remember', 'remember feel', 'feel like', 'like lol']
Document 31 2-grams (sequential): ['wait still', 'still clear', 'clear sure', 'sure sarcastic', 'sarcastic x', 'x want', 'want live', 'live u']
Document 32 2-grams (sequential): ['yeah got', 'got v', 'v apologetic', 'apologetic n', 'n fallen', 'fallen actin', 'actin like', 'like spoilt', 'spoilt child', 'child got', 'got caught', 'caught till', 'till go', 'go badly', 'badly cheer']
Document 33 2-grams (sequential): ['k tell', 'tell anything']
Document 34 2-grams (sequential): ['fear fainting', 'fainting housework', 'housework quick', 'quick cuppa']
Document 35 2-grams (sequential): ['thanks subscription', 'subscription ringtone', 'ringtone uk', 'uk mobile', 'mobile charged', 'charged month', 'month please', 'please confirm', 'confirm replying', 'replying yes', 'yes reply', 'reply charged']
Document 36 2-grams (sequential): ['yup ok', 'ok go', 'go home', 'home look', 'look timing', 'timing msg', 'msg xuhui', 'xuhui going', 'going learn', 'learn nd', 'nd may', 'may lesson']
Document 37 2-grams (sequential): ['oops let', 'let know', 'know roommate', 'roommate done']
Document 38 2-grams (sequential): ['see letter', 'letter b', 'b car']
Document 39 2-grams (sequential): ['anything lor', 'lor u', 'u decide']
Document 40 2-grams (sequential): ['hello saturday', 'saturday go', 'go texting', 'texting see', 'see decided', 'decided anything', 'anything tomo', 'tomo trying', 'trying invite', 'invite anything']
Document 41 2-grams (sequential): ['pls go', 'go ahead', 'ahead watt', 'watt wanted', 'wanted sure', 'sure great', 'great weekend', 'weekend abiola']
Document 42 2-grams (sequential): ['forget tell', 'tell want', 'want need', 'need crave', 'crave love', 'love sweet', 'sweet arabian', 'arabian steed', 'steed mmmmmm', 'mmmmmm yummy']
Document 43 2-grams (sequential): ['rodger burn', 'burn msg', 'msg tried', 'tried call', 'call reply', 'reply sm', 'sm free', 'free nokia', 'nokia mobile', 'mobile free', 'free camcorder', 'camcorder please', 'please call', 'call delivery', 'delivery tomorrow']
Document 44 2-grams (sequential): []
Document 45 2-grams (sequential): ['great hope', 'hope like', 'like man', 'man well', 'well endowed', 'endowed lt', 'lt gt', 'gt inch']
Document 46 2-grams (sequential): ['call message', 'message missed', 'missed call']
Document 47 2-grams (sequential): ['get hep', 'hep b', 'b immunisation', 'immunisation nigeria']
Document 48 2-grams (sequential): ['fair enough', 'enough anything', 'anything going']
Document 49 2-grams (sequential): ['yeah hopefully', 'hopefully tyler', 'tyler could', 'could maybe', 'maybe ask', 'ask around', 'around bit']
Document 50 2-grams (sequential): ['u know', 'know stubborn', 'stubborn even', 'even want', 'want go', 'go hospital', 'hospital kept', 'kept telling', 'telling mark', 'mark weak', 'weak sucker', 'sucker hospital', 'hospital weak', 'weak sucker']
Document 51 2-grams (sequential): ['thinked first', 'first time', 'time saw', 'saw class']
Document 52 2-grams (sequential): ['gram usually', 'usually run', 'run like', 'like lt', 'lt gt', 'gt half', 'half eighth', 'eighth smarter', 'smarter though', 'though get', 'get almost', 'almost whole', 'whole second', 'second gram', 'gram lt', 'lt gt']
Document 53 2-grams (sequential): ['k fyi', 'fyi x', 'x ride', 'ride early', 'early tomorrow', 'tomorrow morning', 'morning crashing', 'crashing place', 'place tonight']
Document 54 2-grams (sequential): ['wow never', 'never realized', 'realized embarassed', 'embarassed accomodations', 'accomodations thought', 'thought liked', 'liked since', 'since best', 'best could', 'could always', 'always seemed', 'seemed happy', 'happy cave', 'cave sorry', 'sorry give', 'give sorry', 'sorry offered', 'offered sorry', 'sorry room', 'room embarassing']
Document 55 2-grams (sequential): ['sm ac', 'ac sptv', 'sptv new', 'new jersey', 'jersey devil', 'devil detroit', 'detroit red', 'red wing', 'wing play', 'play ice', 'ice hockey', 'hockey correct', 'correct incorrect', 'incorrect end', 'end reply', 'reply end', 'end sptv']
Document 56 2-grams (sequential): ['know mallika', 'mallika sherawat', 'sherawat yesterday', 'yesterday find', 'find lt', 'lt url', 'url gt']
Document 57 2-grams (sequential): ['congrats year', 'year special', 'special cinema', 'cinema pas', 'pas call', 'call c', 'c suprman', 'suprman v', 'v matrix', 'matrix starwars', 'starwars etc', 'etc free', 'free bx', 'bx ip', 'ip pm', 'pm dont', 'dont miss']
Document 58 2-grams (sequential): ['sorry call', 'call later', 'later meeting']
Document 59 2-grams (sequential): ['tell reached']
Document 60 2-grams (sequential): ['yes gauti', 'gauti sehwag', 'sehwag odi', 'odi series']
Document 61 2-grams (sequential): ['gonna pick', 'pick burger', 'burger way', 'way home', 'home even', 'even move', 'move pain', 'pain killing']
Document 62 2-grams (sequential): ['ha ha', 'ha ha', 'ha good', 'good joke', 'joke girl', 'girl situation', 'situation seeker']
Document 63 2-grams (sequential): ['part checking', 'checking iq']
Document 64 2-grams (sequential): ['sorry roommate', 'roommate took', 'took forever', 'forever ok', 'ok come']
Document 65 2-grams (sequential): ['ok lar', 'lar double', 'double check', 'check wif', 'wif da', 'da hair', 'hair dresser', 'dresser already', 'already said', 'said wun', 'wun cut', 'cut v', 'v short', 'short said', 'said cut', 'cut look', 'look nice']
Document 66 2-grams (sequential): ['valued customer', 'customer pleased', 'pleased advise', 'advise following', 'following recent', 'recent review', 'review mob', 'mob awarded', 'awarded bonus', 'bonus prize', 'prize call']
Document 67 2-grams (sequential): ['today song', 'song dedicated', 'dedicated day', 'day song', 'song u', 'u dedicate', 'dedicate send', 'send ur', 'ur valuable', 'valuable frnds', 'frnds first', 'first rply']
Document 68 2-grams (sequential): ['urgent ur', 'ur awarded', 'awarded complimentary', 'complimentary trip', 'trip eurodisinc', 'eurodisinc trav', 'trav aco', 'aco entry', 'entry claim', 'claim txt', 'txt dis', 'dis morefrmmob', 'morefrmmob shracomorsglsuplt', 'shracomorsglsuplt l', 'l aj']
Document 69 2-grams (sequential): ['hear new', 'new divorce', 'divorce barbie', 'barbie come', 'come ken', 'ken stuff']
Document 70 2-grams (sequential): ['plane give', 'give month', 'month end']
Document 71 2-grams (sequential): ['wah lucky', 'lucky man', 'man save', 'save money', 'money hee']
Document 72 2-grams (sequential): ['finished class']
Document 73 2-grams (sequential): ['hi babe', 'babe im', 'im home', 'home wanna', 'wanna something', 'something xx']
Document 74 2-grams (sequential): ['k k', 'k performed']
Document 75 2-grams (sequential): ['u call']
Document 76 2-grams (sequential): ['waiting machan', 'machan call', 'call free']
Document 77 2-grams (sequential): ['thats cool', 'cool gentleman', 'gentleman treat', 'treat dignity', 'dignity respect']
Document 78 2-grams (sequential): ['like people', 'people much', 'much shy', 'shy pa']
Document 79 2-grams (sequential): ['operate lt', 'lt gt']
Document 80 2-grams (sequential): ['still looking', 'looking job', 'job much', 'much ta', 'ta earn']
Document 81 2-grams (sequential): ['sorry call', 'call later']
Document 82 2-grams (sequential): ['k call', 'call ah']
Document 83 2-grams (sequential): ['ok way', 'way home', 'home hi', 'hi hi']
Document 84 2-grams (sequential): ['place man']
Document 85 2-grams (sequential): ['yup next', 'next stop']
Document 86 2-grams (sequential): ['call later', 'later network', 'network urgnt', 'urgnt sm']
Document 87 2-grams (sequential): ['real u', 'u getting', 'getting yo', 'yo need', 'need ticket', 'ticket one', 'one jacket', 'jacket done', 'done already', 'already used', 'used multis']
Document 88 2-grams (sequential): ['yes started', 'started send', 'send request', 'request make', 'make pain', 'pain came', 'came back', 'back back', 'back bed', 'bed double', 'double coin', 'coin factory', 'factory gotta', 'gotta cash', 'cash nitros']
Document 89 2-grams (sequential): ['really still', 'still tonight', 'tonight babe']
Document 90 2-grams (sequential): ['ela kano', 'kano il', 'il download', 'download come', 'come wen', 'wen ur', 'ur free']
Document 91 2-grams (sequential): ['yeah stand', 'stand close', 'close tho', 'tho catch', 'catch something']
Document 92 2-grams (sequential): ['sorry pain', 'pain ok', 'ok meet', 'meet another', 'another night', 'night spent', 'spent late', 'late afternoon', 'afternoon casualty', 'casualty mean', 'mean done', 'done stuff', 'stuff moro', 'moro includes', 'includes time', 'time sheet', 'sheet sorry']
Document 93 2-grams (sequential): ['smile pleasure', 'pleasure smile', 'smile pain', 'pain smile', 'smile trouble', 'trouble pours', 'pours like', 'like rain', 'rain smile', 'smile sum', 'sum hurt', 'hurt u', 'u smile', 'smile becoz', 'becoz someone', 'someone still', 'still love', 'love see', 'see u', 'u smiling']
Document 94 2-grams (sequential): ['please call', 'call customer', 'customer service', 'service representative', 'representative pm', 'pm guaranteed', 'guaranteed cash', 'cash prize']
Document 95 2-grams (sequential): ['havent planning', 'planning buy', 'buy later', 'later check', 'check already', 'already lido', 'lido got', 'got show', 'show e', 'e afternoon', 'afternoon u', 'u finish', 'finish work', 'work already']
Document 96 2-grams (sequential): ['free ringtone', 'ringtone waiting', 'waiting collected', 'collected simply', 'simply text', 'text password', 'password mix', 'mix verify', 'verify get', 'get usher', 'usher britney', 'britney fml']
Document 97 2-grams (sequential): ['watching telugu', 'telugu movie', 'movie wat', 'wat abt', 'abt u']
Document 98 2-grams (sequential): ['see finish', 'finish load', 'load loan', 'loan pay']
Document 99 2-grams (sequential): ['hi wk', 'wk ok', 'ok hols', 'hols yes', 'yes bit', 'bit run', 'run forgot', 'forgot hairdresser', 'hairdresser appointment', 'appointment four', 'four need', 'need get', 'get home', 'home n', 'n shower', 'shower beforehand', 'beforehand cause', 'cause prob', 'prob u', 'u ham']
Document 100 2-grams (sequential): ['please text', 'text anymore', 'anymore nothing', 'nothing else', 'else say']
Document 101 2-grams (sequential): ['okay name', 'name ur', 'ur price', 'price long', 'long legal', 'legal wen', 'wen pick', 'pick u', 'u ave', 'ave x', 'x am', 'am xx']
Document 102 2-grams (sequential): ['still looking', 'looking car', 'car buy', 'buy gone', 'gone driving', 'driving test', 'test yet']
Document 103 2-grams (sequential): ['wow right', 'right mean', 'mean guess', 'guess gave', 'gave boston', 'boston men', 'men changed', 'changed search', 'search location', 'location nyc', 'nyc something', 'something changed', 'changed cuz', 'cuz signin', 'signin page', 'page still', 'still say', 'say boston']
Document 104 2-grams (sequential): ['umma life', 'life vava', 'vava umma', 'umma love', 'love lot', 'lot dear']
Document 105 2-grams (sequential): ['thanks lot', 'lot wish', 'wish birthday', 'birthday thanks', 'thanks making', 'making birthday', 'birthday truly', 'truly memorable']
Document 106 2-grams (sequential): ['aight hit', 'hit get', 'get cash']
Document 107 2-grams (sequential): ['would ip', 'ip address', 'address test', 'test considering', 'considering computer', 'computer minecraft', 'minecraft server']
Document 108 2-grams (sequential): ['know grumpy', 'grumpy old', 'old people', 'people mom', 'mom like', 'like better', 'better lying', 'lying always', 'always one', 'one play', 'play joke']
Document 109 2-grams (sequential): ['dont worry', 'worry guess', 'guess busy']
Document 110 2-grams (sequential): ['plural noun', 'noun research']
Document 111 2-grams (sequential): ['going dinner', 'dinner msg']
Document 112 2-grams (sequential): ['ok wif', 'wif co', 'co like', 'like try', 'try new', 'new thing', 'thing scared', 'scared u', 'u dun', 'dun like', 'like mah', 'mah co', 'co u', 'u said', 'said loud']
Document 113 2-grams (sequential): ['gent trying', 'trying contact', 'contact last', 'last weekend', 'weekend draw', 'draw show', 'show prize', 'prize guaranteed', 'guaranteed call', 'call claim', 'claim code', 'code k', 'k valid', 'valid hr', 'hr ppm']
Document 114 2-grams (sequential): ['wa ur', 'ur openin', 'openin sentence', 'sentence formal', 'formal anyway', 'anyway fine', 'fine juz', 'juz tt', 'tt eatin', 'eatin much', 'much n', 'n puttin', 'puttin weight', 'weight haha', 'haha anythin', 'anythin special', 'special happened']
Document 115 2-grams (sequential): ['entered cabin', 'cabin pa', 'pa said', 'said happy', 'happy b', 'b day', 'day bos', 'bos felt', 'felt special', 'special askd', 'askd lunch', 'lunch lunch', 'lunch invited', 'invited apartment', 'apartment went']
Document 116 2-grams (sequential): ['winner u', 'u specially', 'specially selected', 'selected receive', 'receive holiday', 'holiday flight', 'flight inc', 'inc speak', 'speak live', 'live operator', 'operator claim', 'claim p', 'p min']
Document 117 2-grams (sequential): ['goodo yes', 'yes must', 'must speak', 'speak friday', 'friday egg', 'egg potato', 'potato ratio', 'ratio tortilla', 'tortilla needed']
Document 118 2-grams (sequential): ['hmm uncle', 'uncle informed', 'informed paying', 'paying school', 'school directly', 'directly pls', 'pls buy', 'buy food']
Document 119 2-grams (sequential): ['private account', 'account statement', 'statement show', 'show unredeemed', 'unredeemed bonus', 'bonus point', 'point claim', 'claim call', 'call identifier', 'identifier code', 'code expires']
Document 120 2-grams (sequential): ['urgent mobile', 'mobile awarded', 'awarded bonus', 'bonus caller', 'caller prize', 'prize final', 'final try', 'try contact', 'contact u', 'u call', 'call landline', 'landline box', 'box wr', 'wr c', 'c ppm']
Document 121 2-grams (sequential): ['new address', 'address apple', 'apple pair', 'pair malarky']
Document 122 2-grams (sequential): ['today voda', 'voda number', 'number ending', 'ending selected', 'selected receive', 'receive award', 'award match', 'match please', 'please call', 'call quoting', 'quoting claim', 'claim code', 'code standard', 'standard rate', 'rate app']
Document 123 2-grams (sequential): ['going sao', 'sao mu', 'mu today', 'today done']
Document 124 2-grams (sequential): ['predict wat', 'wat time', 'time finish', 'finish buying']
Document 125 2-grams (sequential): ['good stuff']
Document 126 2-grams (sequential): ['know yetunde', 'yetunde sent', 'sent money', 'money yet', 'yet sent', 'sent text', 'text bother', 'bother sending', 'sending dont', 'dont involve', 'involve anything', 'anything imposed', 'imposed anything', 'anything first', 'first place', 'place apologise']
Document 127 2-grams (sequential): []

In [ ]:
vectorizer = CountVectorizer(ngram_range=(2,2))
bow = vectorizer.fit_transform(df2["wordnet_lemmatized_text"])

In [ ]:
vectorizer.get_feature_names_out()

array(['aa exhaust', 'aah bless', 'aah cuddle', ..., 'zoom cine',
       'zouk nichols', 'zyada kisi'], dtype=object)

In [ ]:
bow.toarray()[0].shape

(29627,)

In [ ]:
tfidf_vectorizer = TfidfVectorizer(ngram_range=(2,2))
tfidf = tfidf_vectorizer.fit_transform(df2["wordnet_lemmatized_text"])

In [ ]:
tfidf.toarray()[0].shape

(29627,)

In [ ]:
df3 = pd.DataFrame(tfidf.toarray(),columns = tfidf_vectorizer.get_feature_names_out())

In [ ]:
df2["v1"].isna().sum()

np.int64(0)

In [ ]:
df3 = df3.reset_index(drop=True)
label = df2["v1"].reset_index(drop=True)

In [ ]:
df3["label"] = label

In [ ]:
df3["label"].isna().sum()

np.int64(0)

In [ ]:
x = df3.drop(columns=["label"])
y = df3["label"]

In [ ]:
xtrain , xtest , ytrain , ytest = train_test_split(x,y,test_size=0.2 , random_state = 7)

In [ ]:
model = RandomForestClassifier(n_estimators=100)

In [ ]:
model.fit(xtrain , ytrain)

RandomForestClassifier()

In [ ]:
ypred = model.predict(xtest)

In [ ]:
print(classification_report(ytest , ypred))

              precision    recall  f1-score   support

         ham       0.94      1.00      0.97       886
        spam       1.00      0.64      0.78       148

    accuracy                           0.95      1034
   macro avg       0.97      0.82      0.87      1034
weighted avg       0.95      0.95      0.94      1034

In [ ]:
confusion_matrix(ytest , ypred)

array([[886,   0],
       [ 54,  94]])